version: "3.8"

services:
  # Microservicio de Usuarios
  users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users_api
    ports:
      - "5057:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MongoConnection=mongodb://admin:Your_password123@users_mongodb:27017/UsersDb?authSource=admin
      - RabbitMQHost=rabbitmq
      - RabbitMQPort=5672
      - RabbitMQUser=admin
      - RabbitMQPassword=Your_password123
    external_links:
      - users_mongodb
      - shared_rabbitmq:rabbitmq
    networks:
      - microservices_net
    restart: unless-stopped

networks:
  microservices_net:
    external: true
